
[[ACCOUNTS]]
address = "rwXtered5xDwifU1LDAEira2zQVN57gTBG"
network = "main"
desc = "Ridworld1 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r4WACvo5MF4F67WNYgVbrBRBxUbvYQo3t5"
network = "main"
desc = "Ridworld2 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rpeUegPQ7phkPDt3i6LaMcHd27jnPpJoPJ"
network = "main"
desc = "Ridworld3 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rMAThnVnax3WcXLuYZ94ZtpNtiCvL4SQYZ"
network = "main"
desc = "Ridworld4 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rfBjAa63uJic3Xyz3tPnZwH93qj2ftL7w5"
network = "main"
desc = "Ridworld5 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rpjufc2JYgWZiQeJHoNhzBzRmEQ1JbqzmV"
network = "main"
desc = "Ridworld6 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rPNYYKaDw4R1rwDs579S37wFZ18aNxT9wW"
network = "main"
desc = "Ridworld7 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r9s4EQeCDg3dDnC2qVcdwisYnkQkWppAne"
network = "main"
desc = "Ridworld8 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rn8ZodJs2LpHkZVg2QFd2BT7i9ZfUhF5sd"
network = "main"
desc = "Ridworld9 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rwkACvvYqhHGFvJicCPXJju9oW1sYmwVcL"
network = "main"
desc = "Ridworld10 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rLVuEP27kZ8WzJC5N6xtygspG4GgmMJ3qk"
network = "main"
desc = "Ridworld11 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rJrxMyDFJX1BWkuobT2VCTdhkAGJxYd8Pw"
network = "main"
desc = "Ridworld12 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rnKg6vS9iFS5T2CbCVRnMLBU41yKVZH2hz"
network = "main"
desc = "Ridworld13 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = rDYwhBym9p1Ds7xKhj1xhLNJMGYHMdbcw8""
network = "main"
desc = "Ridworld14 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsLVeC3HQhz7z8KNvRfTG42Tfp4JnMEwMG"
network = "main"
desc = "Ridworld15 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r3h24pJzo6ed3WMsYVRX7kU9pDWkxuCygr"
network = "main"
desc = "Ridworld16 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rLfPYWnYrqWUHz1N7mtrBzoRkrdMPPLHHX"
network = "main"
desc = "Ridworld17 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rwfcm3F2xxfjAdizUU2R3ddFH4KasAecgv"
network = "main"
desc = "Ridworld18 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHKPVGYVpWminFDbbfKFzG6LmdYYjYP9fB"
network = "main"
desc = "Ridworld19 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rDQHs2X7nQGFCx2Jd2XiKn6Zavebz76TT4"
network = "main"
desc = "Ridworld20 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r456WbTdQLkDnrvHGUmY7PcULAAX3upCPV"
network = "main"
desc = "Ridworld21 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rEG5DvJP2q9TrQZpYaijs6NP9PhWdr9brV"
network = "main"
desc = "Ridworld22 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHSLoFTELgAwpMzFM8sZq6pdWeEWxiSdQQ"
network = "main"
desc = "Ridworld23 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rBGYPSiM5wmvbjHL9nMvfjEJWWRv2ZAkRs"
network = "main"
desc = "Ridworld24 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rUtjuVgKzDQFJcAZgeX4NC6UE9jfYRGR4u"
network = "main"
desc = "Ridworld25 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rUAF7WhpZd7QTkBbqZSECUos1eCpBDwv3w"
network = "main"
desc = "Ridworld26 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rGw4ryUroPK7xrMyYkc7DKe4cjiuAseNfb"
network = "main"
desc = "Ridworld27 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsVH14CjsFgBsoZMxzs2swmP5HxewdNddB"
network = "main"
desc = "Ridworld28 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rESq3xxje1rQxX3Ss3LEjbXq4GRTS949o3"
network = "main"
desc = "Ridworld29 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsrsg86KCnqESPdzV2swuqwXXNyCNqjR1x"
network = "main"
desc = "Ridworld30 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rnEHGwHsCegzorExTgG35t8isdPbVd7862"
network = "main"
desc = "Ridworld31 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r4BYNXdS6cGk4NhkhHU6Dke63bJzNgqLYN"
network = "main"
desc = "Ridworld32 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rpeGpMRhWQ9cKHRQba8WeN3buhnJbZXbs5"
network = "main"
desc = "Ridworld33 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rwrbkqPAJEZoDr844xxTFv72P935p9nk8c"
network = "main"
desc = "Ridworld34 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rNj9YerzfFw8B4cZFqg2HDU8EhKzEq2agV"
network = "main"
desc = "Ridworld35 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsqx4NFdmpv71wq5BQmnvZ6Mqk9fiQa3D1"
network = "main"
desc = "Ridworld36 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rapMUL11cnMqa3hiYp9XS5LieVNYsVWCbE"
network = "main"
desc = "Ridworld37 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r9ewmx6W7an3Hi41n8JYhSVbfiS7zph7w3"
network = "main"
desc = "Ridworld38 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rfbziFZkupKshiYGt4UnhYCG8E8wiGQetd"
network = "main"
desc = "Ridworld39 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rdJYeZFWLojf52hugAXh2DN5ALcdPUwKE"
network = "main"
desc = "Ridworld40 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rKhsWYAVuxhXNwAtwpj6Bpa8jfucUSZw6T"
network = "main"
desc = "Ridworld41 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r4QS1ShbV4YFZUFrVU5gngZWFuyUAncGpM"
network = "main"
desc = "Ridworld42 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rpsYZbPj4M9JM7GzEz56erRTuMhVgt2JiG"
network = "main"
desc = "Ridworld43 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rE73xmMeKmQiTs99qgn3PsDBc8DeQqE3Gx"
network = "main"
desc = "Ridworld44 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rDp7T9kfLUVksZUrDhxcsK3wDQcnmYriJS"
network = "main"
desc = "Ridworld45 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rKFar4TmpiT5fEiL2fv84UbSY5Vv6umkhP"
network = "main"
desc = "Ridworld46 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rM296NisYjypgCCJvL4YyBJjx4JygLDi2k"
network = "main"
desc = "Ridworld47 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r488rhYNsHUGyzsqpZrELcWLz6CSXhwSca"
network = "main"
desc = "Ridworld48 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "raigwQ2uSx2nTZFyCQHR6XFWjR9FJw7goe"
network = "main"
desc = "Ridworld49 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rfzFsapZH4L4ybUpk1qwCzmf93ZsBnh3UC"
network = "main"
desc = "Ridworld50 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r957yeMPXNqJz2Ne2E5v7mTb3Z5vv4SKKM"
network = "main"
desc = "Ridworld51 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rwRDExhxSKBriXgvyDvWH8K9qKb3pfX9pn"
network = "main"
desc = "Ridworld52 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rLP87gQbzJUGesjgwMkSJ42WLp7Ty76ckr"
network = "main"
desc = "Ridworld53 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rstLJ9AHiedXTeoTwn4cD7a6nSxQwkonUB"
network = "main"
desc = "Ridworld54 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rD7vmJnFxWCoooPQa3KUfpT6u6gRd8FbKJ"
network = "main"
desc = "Ridworld55 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r95gi24S3FK7vkV6keu2CKfocCbdyCskZ9"
network = "main"
desc = "Ridworld56 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rJCtVSQ6vmmdfy33W583zhzcFqrVzn5Z1d"
network = "main"
desc = "Ridworld57 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rMWunTj1oGj6GJJc2X4BihVTeTacTEyLTa"
network = "main"
desc = "Ridworld58 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsVYAtkWxKTFifLKcc2D76eNVB4ArU4Shg"
network = "main"
desc = "Ridworld59 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rGn4fsB5KU3xZ3VDB88aK9w265nru6bNwQ"
network = "main"
desc = "Ridworld60 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHuCdCw3bqtAxVebc17QJ45wnEkGhAx5YL"
network = "main"
desc = "Ridworld61 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rdYLywuQkF2mB4K3msgtmZWZoVTqJYEw3"
network = "main"
desc = "Ridworld62 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rpyj1JSJvBKoTsyP6WkcRB3P9NSJaQZQ11"
network = "main"
desc = "Ridworld63 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rh73VvU9dNSLmcypTV128v7w4szSjMAM2o"
network = "main"
desc = "Ridworld64 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rBywuLcQsAZbFKfNZevwDmt8LNatr6dGjj"
network = "main"
desc = "Ridworld65 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rM4JQdPvavuRWSpBxRP7x1U11YuHRooBVF"
network = "main"
desc = "Ridworld66 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsHkAvX4nDsjbf64zFXLXEcbeiiPYBM8L8"
network = "main"
desc = "Ridworld67 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rBa7KLLKeNXu4XNhH3ptbS87Tmzv56ap8w"
network = "main"
desc = "Ridworld68 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r3ejUsBW3hVYZ2DrcxbrRLtNxxv6iL14UE"
network = "main"
desc = "Ridworld69 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rNq3ef7KdUBGP7snB2YCJ5FwDheaknD1mw"
network = "main"
desc = "Ridworld70 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rnj3qkjqa5tRTwurgHwmgsCG9MExoEvGNg"
network = "main"
desc = "Ridworld71 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHHTWDyosapZ4yMCf2xTAY1uaw1Dt8KBWq"
network = "main"
desc = "Ridworld72 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHqhTZ3sScJkLpT8Q46V2FsbHrE1eQwQkP"
network = "main"
desc = "Ridworld73 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHrfvNRwnxxfDEs2d15umeyFqmMp4TNY3E"
network = "main"
desc = "Ridworld74 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rKv6sjM28hjEnvbNpsdVmAVFrM8ZrSMz6S"
network = "main"
desc = "Ridworld75 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsd9KB8wy89hxZK7xovrwUBnm3BDM9L36B"
network = "main"
desc = "Ridworld76 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rH57UJYTB1x8PUpxVYFyZGpEFQ6EvNaEBd"
network = "main"
desc = "Ridworld77 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r4GKhqihzzj9dcrkgzTpv9xXiL9bWtTG9P"
network = "main"
desc = "Ridworld78 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rR3T3wbZgXAbph5N8KpM2rX6NoUsmzPqR"
network = "main"
desc = "Ridworld79 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rw6sdKfcorntaQ1SB4LRfKxEeu2e3nNoN3"
network = "main"
desc = "Ridworld80 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHfUSnEnHMBSXeF27H9q63tLYiUcE49AET"
network = "main"
desc = "Ridworld81 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rEVFpqdoZqGkZmAyNFJ93ScjHG8BtRc5cs"
network = "main"
desc = "Ridworld82 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rwPmmJiSgcBtwv1RYeCfydFLZpn5G8BSj"
network = "main"
desc = "Ridworld83 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rhbLdF8iJ9qm78fi6Lwz9EMCh9MieBNPFg"
network = "main"
desc = "Ridworld84 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rccXvBrc6Tdqc6ZESk9aRd5RpYmc4PbPa"
network = "main"
desc = "Ridworld85 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHoPhg8txJQyFNzNSwV2BXQQ8e9HPNr3P8"
network = "main"
desc = "Ridworld86 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rfjuiehRwRVe3p6KVQBFNz6ZC9EboFiuRB"
network = "main"
desc = "Ridworld87 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rwSfnjTUrDzRSXk7r5LaEDroKzALbewWfa"
network = "main"
desc = "Ridworld88 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rLCPBeGu2MPkDMFKE4DjWgkANkPeS9RfuJ"
network = "main"
desc = "Ridworld89 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r4VGSC2gAqMHgN4hxf5PtTqGjn5xGG4Y9d"
network = "main"
desc = "Ridworld90 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rNKv9YRvcg9APo3sqrusnSYxG1afXTxwrM"
network = "main"
desc = "Ridworld91 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHo7EogvYofhVmKz5vEhQUd74DybwL67Py"
network = "main"
desc = "Ridworld92 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rpu5L6Ef35d1nQ1VNsfhFMM2w8Aea9soZv"
network = "main"
desc = "Ridworld93 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rE7Ngd5f3aGC6CTGjLqAaaZnvZjvez1cBq"
network = "main"
desc = "Ridworld94 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r4gFE4tkhNNSW4jwtdVFcoFdeMXEriuYgR"
network = "main"
desc = "Ridworld95 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rp4ahHP1b6ez9pVHBFCjY1ehhwu6z1us9s"
network = "main"
desc = "Ridworld96 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rhzbXUKpPiKEBE9siW5Qu52YZgbYXDwDzS"
network = "main"
desc = "Ridworld97 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHSMXvBK1TdnHm3eoBXbuthnpT9fcfKwYU"
network = "main"
desc = "Ridworld98 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rBneGziBh2i24bwPjAutSGtjSrb9sk5DjK"
network = "main"
desc = "Ridworld99 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rwtDAR2oGivPeZ3utWVDUhMwv2oAQSJj1M"
network = "main"
desc = "Ridworld100 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rJ8yKZj4JkMA2euJZq4vc5VtA7AYbrjL9K"
network = "main"
desc = "Ridworld101 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r3PHZXHLB5F2dnTNXe9b5f8dqHJsqBd9vS"
network = "main"
desc = "Ridworld102 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsmzA6HFPumovk6asRTe6ayK54zxtEvMnW"
network = "main"
desc = "Ridworld103 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rUyjCKJAivHhnWEG1A31muwc8FhtYJ8EJ5"
network = "main"
desc = "Ridworld104 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rGazqHbNQx4J7MravYuq3EuaX7iKvzyeut"
network = "main"
desc = "Ridworld105 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rLaTSW1X5nCiWJXrUYAQcDzyGUx1pVVqx"
network = "main"
desc = "Ridworld106 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rhdfjXDuhn6ZrYgzWJP2fGjyTTo5k4ahLM"
network = "main"
desc = "Ridworld107 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rsojYoSWpQFp2SQqy81jJhZRwyjPFovvmw"
network = "main"
desc = "Ridworld108 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rHVyg5sFw62LMvAvZiPhEqBDuXYWGaYe7w"
network = "main"
desc = "Ridworld109 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rBpg2g5ZtAscEqwjebUaRj2cQMoXoFfsi2"
network = "main"
desc = "Ridworld110 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rNyMjk9e4zvPKzpsK5s5qtDMhGjidUue3v"
network = "main"
desc = "Ridworld111 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "r49g8ae8665sSG3AFWc4jjg1TiSm2RBdEi"
network = "main"
desc = "Ridworld112 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rKVwZJXf89HMsYGcLFya9g1KqFtxydvPFt"
network = "main"
desc = "Ridworld113 NFT Card Genesis Edition"

[[ACCOUNTS]]
address = "rK4tKY7zgUvEwh8FfuBGSDjT7WxQHyTSF1"
network = "main"
desc = "RidworldLogo NFT Card Black Logo Especial Edition"

[[ACCOUNTS]]
address = "rJ2R9qKb2Ctrp9Nna2N8QqSrtU3XoTgkM1"
network = "main"
desc = "RWRipplers NFT Card White Logo Especial Edition"

[[ACCOUNTS]]
address = "rUcmsaCPcbS6wg3dT83vWsUz7nPrVrw1kV"
network = "main"
desc = "Serial Numer 0 Ridworld NFTs"

[[ACCOUNTS]]
address = "rpcrwqRrpvZ5Dviaxw8PqhHsU3Tr6VH7n8"
network = "main"
desc = "Enigma's Deck"

[[ACCOUNTS]]
address = "raYWM6yDQtJ1NzrBdBd61bk2rvrF1hvTuH"
network = "main"
desc = "Enigma's Collection"

[[ACCOUNTS]]
address = "r4VzEm7Jbgg3QkPBgMscoppz6JuzK2Jkbd"
network = "main"
desc = "Ridworld main account"

[[PRINCIPALS]]
name = "Enigma Ridworld" 
email = "ridworldgame@tutanota.com" 

# End of file